name: 'diffle_shop'
config-version: 2
version: '1.0.0'
require-dbt-version: [">=1.9.0", "<2.0.0"]
profile: 'diffle_shop'

vars:
  # Configuration for data-diff tool
  data_diff:
    prod_database: main
    prod_schema: prod

# Model configurations
models:
  diffle_shop:
    materialized: table
    +docs:
      show: true
    +meta:
      owner: "Data Team"

# Test configurations
tests:
  diffle_shop:
    +severity: error

# Snapshot configurations
snapshots:
  diffle_shop:
    +target_schema: snapshots

# Seed configurations
seeds:
  diffle_shop:
    +schema: seeds

# Enable documentation and source freshness
on-run-start:
  - "{{ register_upstream_external_models() }}"

# Clean hooks
on-run-end:
  - "{{ log('dbt run completed successfully!', info=true) }}"
