name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  PYTHON_VERSION: "3.11"

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    
    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run pre-commit hooks
      run: |
        pre-commit run --all-files
    
    - name: Check dbt project
      run: |
        dbt debug --profiles-dir .
        dbt parse --profiles-dir .
    
    - name: Run dbt tests
      run: |
        dbt deps --profiles-dir .
        dbt run --profiles-dir . --target dev
        dbt test --profiles-dir . --target dev
    
    - name: Generate dbt docs
      run: |
        dbt docs generate --profiles-dir . --target dev
    
    - name: Upload dbt artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: dbt-artifacts
        path: |
          target/
          logs/

  data-diff-test:
    runs-on: ubuntu-latest
    needs: lint-and-test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run production models
      run: |
        dbt run -s simple_model --target prod --profiles-dir .
    
    - name: Run development models
      run: |
        dbt run -s simple_model --target dev --profiles-dir .
    
    - name: Test data-diff functionality
      run: |
        data-diff --dbt --dbt-profiles-dir .
    
    - name: Upload data-diff results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: data-diff-results
        path: |
          target/
          *.duckdb